// <auto-generated />
using FinalProject2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProject2.Migrations
{
    [DbContext(typeof(BookContext))]
    partial class BookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject2.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BookName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Book");

                    b.UseTphMappingStrategy();

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorName = "Boichi",
                            BookName = "Sun Ken Rock Vol.1",
                            Img = "01-Ken.jpg",
                            Isbn = "978-8861230767",
                            PublishYear = 2006
                        },
                        new
                        {
                            BookId = 2,
                            AuthorName = "Boichi",
                            BookName = "Dr. Stone Vol.1",
                            Img = "02-DrStone.jpg",
                            Isbn = "978-1-9747-0261-9",
                            PublishYear = 2017
                        },
                        new
                        {
                            BookId = 3,
                            AuthorName = "Boichi",
                            BookName = "Origin",
                            Img = "03-Origin_(manga)_1.png",
                            Isbn = "978-1-64-729287-4",
                            PublishYear = 2016
                        },
                        new
                        {
                            BookId = 4,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen 0",
                            Img = "04-Jujutsu_Kaisen_0_Cover.png",
                            Isbn = "978-4-08-881672-2",
                            PublishYear = 2017
                        },
                        new
                        {
                            BookId = 5,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol.8",
                            Img = "05-Volume_8.jpg",
                            Isbn = "978-4-08-882168-9",
                            PublishYear = 2020
                        },
                        new
                        {
                            BookId = 6,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol.1",
                            Img = "06-Volume_1.jpg",
                            Isbn = "978-4-08-881516-9",
                            PublishYear = 2018
                        },
                        new
                        {
                            BookId = 7,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol.4 ",
                            Img = "07-Volume_4.jpg",
                            Isbn = "978-4-08-881756-9",
                            PublishYear = 2019
                        },
                        new
                        {
                            BookId = 8,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol.5",
                            Img = "08-Volume_5.jpg",
                            Isbn = "978-4-08-881828-3",
                            PublishYear = 2019
                        },
                        new
                        {
                            BookId = 9,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol.7",
                            Img = "09-Volume_7.jpg",
                            Isbn = "978-4-08-882076-7",
                            PublishYear = 2019
                        },
                        new
                        {
                            BookId = 10,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol.14",
                            Img = "10-Volume_14.jpg",
                            Isbn = "978-4-08-882534-2",
                            PublishYear = 2021
                        },
                        new
                        {
                            BookId = 11,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol. 17",
                            Img = "11-Volume_17.jpg",
                            Isbn = "978-4-08-882736-0",
                            PublishYear = 2021
                        },
                        new
                        {
                            BookId = 12,
                            AuthorName = "Gege Akutami",
                            BookName = "Jujutsu Kaisen Vol.22",
                            Img = "12-Volume_22.jpg",
                            Isbn = "978-4-08-883434-4",
                            PublishYear = 2023
                        },
                        new
                        {
                            BookId = 13,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.85",
                            Img = "13-Volume_85.jpg",
                            Isbn = "978-4-08-881070-6",
                            PublishYear = 2017
                        },
                        new
                        {
                            BookId = 14,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.86",
                            Img = "14-Volume_86.jpg",
                            Isbn = "978-4-08-881198-7",
                            PublishYear = 2017
                        },
                        new
                        {
                            BookId = 15,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.87",
                            Img = "15-Volume_87.jpg",
                            Isbn = "978-4-08-881225-0",
                            PublishYear = 2017
                        },
                        new
                        {
                            BookId = 16,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.88",
                            Img = "16-Volume_88.jpg",
                            Isbn = "978-4-08-881362-2",
                            PublishYear = 2018
                        },
                        new
                        {
                            BookId = 17,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.89",
                            Img = "17-Volume_89.jpg",
                            Isbn = "978-4-08-881496-4",
                            PublishYear = 2018
                        },
                        new
                        {
                            BookId = 18,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.90",
                            Img = "18-Volume_90.jpg",
                            Isbn = "978-4-08-881562-6",
                            PublishYear = 2018
                        },
                        new
                        {
                            BookId = 19,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.91",
                            Img = "19-Volume_91.jpg",
                            Isbn = "978-4-08-881644-9",
                            PublishYear = 2018
                        },
                        new
                        {
                            BookId = 20,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.92",
                            Img = "20-Volume_92.jpg",
                            Isbn = "978-4-08-881758-3",
                            PublishYear = 2019
                        },
                        new
                        {
                            BookId = 21,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.93",
                            Img = "21-Volume_93.jpg",
                            Isbn = "978-4-08-881877-1",
                            PublishYear = 2019
                        },
                        new
                        {
                            BookId = 22,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.94",
                            Img = "22-Volume_94.jpg",
                            Isbn = "978-4-08-882054-5",
                            PublishYear = 2019
                        },
                        new
                        {
                            BookId = 23,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.95",
                            Img = "23-Volume_95.jpg",
                            Isbn = "978-4-08-882169-6",
                            PublishYear = 2019
                        },
                        new
                        {
                            BookId = 24,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.96",
                            Img = "24-Volume_96.jpg",
                            Isbn = "978-4-08-882252-5",
                            PublishYear = 2020
                        },
                        new
                        {
                            BookId = 25,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.97",
                            Img = "25-Volume_97.jpg",
                            Isbn = "978-4-08-882347-8",
                            PublishYear = 2020
                        },
                        new
                        {
                            BookId = 26,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.98",
                            Img = "26-Volume_98.jpg",
                            Isbn = "978-4-08-882423-9",
                            PublishYear = 2021
                        },
                        new
                        {
                            BookId = 27,
                            AuthorName = "Eiichiro Oda",
                            BookName = "One Piece Vol.99",
                            Img = "27-Volume_99.jpg",
                            Isbn = "978-4-08-882691-2",
                            PublishYear = 2021
                        });
                });

            modelBuilder.Entity("FinalProject2.Review", b =>
                {
                    b.HasBaseType("FinalProject2.Book");

                    b.Property<int>("BookNumber")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Review");
                });
#pragma warning restore 612, 618
        }
    }
}
